# Generated by Django 5.1.4 on 2025-01-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatehistory',
            name='src_lang',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='translatehistory',
            name='trans_lang',
            field=models.CharField(default='', max_length=10),
        ),
    ]
